table BPS_20_26_LourencoFLemos
	lineageTag: ed9160d2-0306-42f7-8c3e-148b69e23e89

	column ano_compra
		dataType: int64
		formatString: 0
		lineageTag: 9036c95f-368f-41da-b3e9-fff8614e63f1
		summarizeBy: sum
		sourceColumn: ano_compra

		annotation SummarizationSetBy = Automatic

	column nome_instituicao
		dataType: string
		lineageTag: 06e031a8-3794-4fe5-a62c-d1beff888bcd
		summarizeBy: none
		sourceColumn: nome_instituicao

		annotation SummarizationSetBy = Automatic

	column esfera_instituicao
		dataType: string
		lineageTag: 36667a43-95e7-493d-82db-f1ea9f280c23
		summarizeBy: none
		sourceColumn: esfera_instituicao

		annotation SummarizationSetBy = Automatic

	column cnpj_instituicao
		dataType: int64
		formatString: 0
		lineageTag: e966168c-dbaf-40fc-95d1-40658427dcbb
		summarizeBy: sum
		sourceColumn: cnpj_instituicao

		annotation SummarizationSetBy = Automatic

	column municipio_instituicao
		dataType: string
		lineageTag: 9bc6f95c-2b4d-4185-8396-e70ca7a64e52
		summarizeBy: none
		sourceColumn: municipio_instituicao

		annotation SummarizationSetBy = Automatic

	column uf
		dataType: string
		lineageTag: f2170e03-a423-4c92-9d6c-bb6bf352c3ad
		summarizeBy: none
		sourceColumn: uf

		annotation SummarizationSetBy = Automatic

	column data_compra
		dataType: dateTime
		formatString: Short Date
		lineageTag: 6aa3888e-9e85-4687-a889-ed2c1111ae11
		summarizeBy: none
		sourceColumn: data_compra

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column data_insercao
		dataType: dateTime
		formatString: Short Date
		lineageTag: 46877707-46d0-4fa0-9699-76b825265f6f
		summarizeBy: none
		sourceColumn: data_insercao

		variation Variation
			isDefault
			relationship: bc57602c-709d-4830-a52c-20d4233c163f
			defaultHierarchy: LocalDateTable_12d30124-8a32-407d-9e6f-6b08947dba8b.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column codigo_catmat
		dataType: int64
		formatString: 0
		lineageTag: 24bb83c9-bf41-49cf-b427-3f30be509981
		summarizeBy: sum
		sourceColumn: codigo_catmat

		annotation SummarizationSetBy = Automatic

	column descricao_catmat
		dataType: string
		lineageTag: d1bb9a37-2371-48a0-82af-a0e6f128217a
		summarizeBy: none
		sourceColumn: descricao_catmat

		annotation SummarizationSetBy = Automatic

	column unidade_fornecimento
		dataType: string
		lineageTag: a5a0fac4-4bc7-4aa8-93ce-012c5206ccc0
		summarizeBy: none
		sourceColumn: unidade_fornecimento

		annotation SummarizationSetBy = Automatic

	column generico
		dataType: string
		lineageTag: b52fa19b-dede-467a-b12a-511391eceba3
		summarizeBy: none
		sourceColumn: generico

		annotation SummarizationSetBy = Automatic

	column registro_anvisa
		dataType: int64
		formatString: 0
		lineageTag: 9a0e18af-31e3-4796-87e9-796866adcc91
		summarizeBy: sum
		sourceColumn: registro_anvisa

		annotation SummarizationSetBy = Automatic

	column modalidade_compra
		dataType: string
		lineageTag: e05219e9-85c0-49b4-8802-2e33c8445a56
		summarizeBy: none
		sourceColumn: modalidade_compra

		annotation SummarizationSetBy = Automatic

	column tipo_compra
		dataType: string
		lineageTag: 9f13fe98-341c-4a0d-acd0-7fcccb6044c7
		summarizeBy: none
		sourceColumn: tipo_compra

		annotation SummarizationSetBy = Automatic

	column capacidade
		dataType: int64
		formatString: 0
		lineageTag: 251a405d-993c-4df2-b644-79e3885f56ea
		summarizeBy: sum
		sourceColumn: capacidade

		annotation SummarizationSetBy = Automatic

	column unidade_capacidade
		dataType: string
		lineageTag: 3de99b79-63f6-4f0e-a68b-2883034350b4
		summarizeBy: none
		sourceColumn: unidade_capacidade

		annotation SummarizationSetBy = Automatic

	column unidade_fornecimento_capacidade
		dataType: string
		lineageTag: 0dd9517b-0c3e-4641-a40d-ca7054d1ac9e
		summarizeBy: none
		sourceColumn: unidade_fornecimento_capacidade

		annotation SummarizationSetBy = Automatic

	column cnpj_fornecedor
		dataType: int64
		formatString: 0
		lineageTag: 15c3495a-3a75-43b4-8acd-e8102d549280
		summarizeBy: sum
		sourceColumn: cnpj_fornecedor

		annotation SummarizationSetBy = Automatic

	column fornecedor
		dataType: string
		lineageTag: 5976762d-ea5d-40d4-982a-3a967ced3853
		summarizeBy: none
		sourceColumn: fornecedor

		annotation SummarizationSetBy = Automatic

	column cnpj_fabricante
		dataType: int64
		formatString: 0
		lineageTag: 6f0e795c-5e6c-43a8-9cde-588f43d4542a
		summarizeBy: sum
		sourceColumn: cnpj_fabricante

		annotation SummarizationSetBy = Automatic

	column fabricante
		dataType: string
		lineageTag: e0b5f9e0-c18b-4fe8-8c75-7eb31adf9227
		summarizeBy: none
		sourceColumn: fabricante

		annotation SummarizationSetBy = Automatic

	column qtd_itens_comprados
		dataType: int64
		formatString: 0
		lineageTag: fc7c5ae3-9459-4def-a5f9-b191a07709fa
		summarizeBy: sum
		sourceColumn: qtd_itens_comprados

		annotation SummarizationSetBy = Automatic

	column preco_unitario
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: ddbeebab-f218-4f85-8bfd-ca4d352f9946
		summarizeBy: sum
		sourceColumn: preco_unitario

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	column preco_total
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: f4e2dbef-bfc4-4027-8a9f-723b9d0d21ad
		summarizeBy: sum
		sourceColumn: preco_total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	column arquivo_origem
		dataType: string
		lineageTag: 18c09247-e3ec-4006-a525-e01de6113a4a
		summarizeBy: none
		sourceColumn: arquivo_origem

		annotation SummarizationSetBy = Automatic

	partition BPS_20_26_LourencoFLemos = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\Usuário\Downloads\MINI PROJETO PREÇOS SAÚDE\saida\BPS_20_26_LourencoFLemos.csv"),[Delimiter=";", Columns=26, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ano_compra", Int64.Type}, {"nome_instituicao", type text}, {"esfera_instituicao", type text}, {"cnpj_instituicao", Int64.Type}, {"municipio_instituicao", type text}, {"uf", type text}, {"data_compra", type date}, {"data_insercao", type date}, {"codigo_catmat", Int64.Type}, {"descricao_catmat", type text}, {"unidade_fornecimento", type text}, {"generico", type text}, {"registro_anvisa", Int64.Type}, {"modalidade_compra", type text}, {"tipo_compra", type text}, {"capacidade", Int64.Type}, {"unidade_capacidade", type text}, {"unidade_capacidade_1", type text}, {"cnpj_fornecedor", Int64.Type}, {"fornecedor", type text}, {"cnpj_fabricante", Int64.Type}, {"fabricante", type text}, {"qtd_itens_comprados", Int64.Type}, {"preco_unitario", type number}, {"preco_total", type number}, {"arquivo_origem", type text}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"unidade_capacidade_1", "unidade_fornecimento_capacidade"}})
				in
				    #"Colunas Renomeadas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

